name = "Serval"
license = "MIT"
licenselink = "https://github.com/styler3/serval-hugo-theme/blob/master/LICENSE.md"
description = "A simple, minimal and responsive theme"
min_version = 0.18

[author]
  name = "Sam Tyler"
  homepage = "https://samtyler.com.au"
