name = "Serval"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Sam Tyler"
  homepage = "https://samtyler.com.au"
